### ISSUE TITLE
运行时遇到一个奇怪的问题

### ISSUE THREAD

**Issue by XMAN-WOMBAT** [baifendian/CodisClient#13]
系统版本以及glibc版本如下：
![image](https://cloud.githubusercontent.com/assets/20120146/21536148/bca7dbd2-cdb9-11e6-9f09-05b28ccf0ec0.png)

遇到问题提示如下：
![qq 20161229112353](https://cloud.githubusercontent.com/assets/20120146/21536159/e03cd066-cdb9-11e6-84fa-3e4fb69fcc79.png)
通过ldd -r 查看编译链接成功生成的库时，发现 undefined symbol: _ZN4Json6Reader5parseERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_5ValueEb	(./libcodisclient.so)
undefined symbol: _ZNK4Json5Value14toStyledStringB5cxx11Ev	(./libcodisclient.so)
undefined symbol: _ZNK4Json5Value8asStringB5cxx11Ev	(./libcodisclient.so)
看其提示为链接libjson时出的错，但是确实是链接了libjson库。请问下你有遇到这个问题吗？

**Comment by abigbigbird** [comment]
运行时和编译时的gcc版本是否一致？

**Comment by XMAN-WOMBAT** [comment]
@abigbigbird 你好，我编译时是使用的glibc 2.23版本。编译libcodisclient.so没有问题，但是我编译你的Test测试程序时同样提示
![image](https://cloud.githubusercontent.com/assets/20120146/21538635/f9523724-cdd9-11e6-9cd9-8f706895d378.png)
因此我有点怀疑是不是libjson这个库的问题？

**Comment by XMAN-WOMBAT** [comment]
@abigbigbird 请问下libjson库能否提供下该源码或者源码链接？我重新编译下libjson库。谢谢！！！

**Comment by abigbigbird** [comment]
https://github.com/baifendian/CodisClient/tree/master/cpp/3party/lib    在这里有这个libjson的so文件，
你可以试着运行下，source env.sh
然后把https://github.com/baifendian/CodisClient/blob/master/cpp/test/CodisClientDemo.cpp 的12行改成你的codis地址，执行make test 试下

**Comment by XMAN-WOMBAT** [comment]
@abigbigbird  已经测试过了，我将libjson库更新到新版本了，libjsoncpp重新编译后没有发现上述问题。
谢谢你的回答！！！
